/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corridaaleatoria1;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JLabel;
import javax.swing.JFrame;
import javax.swing.ImageIcon;
import java.util.Random;

/**
 *
 * @author Aluno
 */

public class Cenario extends javax.swing.JFrame {
  

    /**
     * Creates new form Cenario
     */
    public Cenario() {
        initComponents();
        ganhador.setVisible(false);
        Perdedor.setVisible(false);
        Ganhador2.setVisible(false);
        Perdedor2.setVisible(false);
        Restart.setVisible(false);
          setSize(750, 500);
          this.setResizable(false);
          mover();
    }
    
    
    
    
    
    int posCarro1X= 100;
    int posCarro1Y= 260;
    int posCarro2X= 100;
    int posCarro2Y= 340;
    char let=68;
    char let1=73;
    char let3=0;
      int [] abecedario = {65, 66, 67, 68 ,69, 70, 71, 72, 73, 
74, 75, 76,77,78,79,80,81,82,83,84,85,86, 87,88,89,90};

int numRandon = (int) Math.round(Math.random() * 25 ) ;
int [] abecedario1 = {65, 66, 67, 68 ,69, 70, 71, 72, 73, 
74, 75, 76,77,78,79,80,81,82,83,84,85,86, 87,88,89,90};

int numRandon1 = (int) Math.round(Math.random() * 25 ) ;
    
    
    //char le[] = {'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'};
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ganhador = new javax.swing.JLabel();
        Ganhador2 = new javax.swing.JLabel();
        Perdedor = new javax.swing.JLabel();
        Perdedor2 = new javax.swing.JLabel();
        Carro2 = new javax.swing.JLabel();
        Carro1 = new javax.swing.JLabel();
        Restart = new javax.swing.JButton();
        Cenario = new javax.swing.JLabel();
        Tecla1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel2.setLayout(null);

        ganhador.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        ganhador.setForeground(new java.awt.Color(0, 204, 51));
        ganhador.setText("CAMPEÃO PARABÉNS");
        jPanel2.add(ganhador);
        ganhador.setBounds(210, 260, 370, 54);

        Ganhador2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        Ganhador2.setForeground(new java.awt.Color(0, 204, 0));
        Ganhador2.setText("CAMPEÃO PARABÉNS");
        jPanel2.add(Ganhador2);
        Ganhador2.setBounds(210, 340, 350, 50);

        Perdedor.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Perdedor.setForeground(new java.awt.Color(204, 0, 0));
        Perdedor.setText("PERDEDOR BOA SORTE PARA A PRÓXIMA");
        jPanel2.add(Perdedor);
        Perdedor.setBounds(220, 350, 340, 50);

        Perdedor2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Perdedor2.setForeground(new java.awt.Color(204, 0, 0));
        Perdedor2.setText("PERDEDOR BOA SORTE PARA A PRÓXIMA");
        jPanel2.add(Perdedor2);
        Perdedor2.setBounds(220, 270, 350, 40);

        Carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corridaaleatoria1/carro2.png"))); // NOI18N
        Carro2.setText("jLabel2");
        Carro2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Carro2KeyReleased(evt);
            }
        });
        jPanel2.add(Carro2);
        Carro2.setBounds(100, 340, 110, 50);

        Carro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corridaaleatoria1/carro.png"))); // NOI18N
        Carro1.setText("carro1");
        Carro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Carro1KeyReleased(evt);
            }
        });
        jPanel2.add(Carro1);
        Carro1.setBounds(100, 260, 100, 40);

        Restart.setText("Click aqui para jogar de novo!");
        Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartActionPerformed(evt);
            }
        });
        jPanel2.add(Restart);
        Restart.setBounds(260, 130, 190, 60);

        Cenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corridaaleatoria1/fundo game.jpg"))); // NOI18N
        jPanel2.add(Cenario);
        Cenario.setBounds(70, -50, 670, 590);

        Tecla1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Tecla1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tecla1.setText("D");
        Tecla1.setBorder(new javax.swing.border.MatteBorder(null));
        Tecla1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tecla1KeyReleased(evt);
            }
        });
        jPanel2.add(Tecla1);
        Tecla1.setBounds(10, 260, 50, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("I");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 340, 50, 50);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Carro1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Carro1KeyReleased





        
    }//GEN-LAST:event_Carro1KeyReleased

    private void Carro2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Carro2KeyReleased
        
        
        
        
        
    }//GEN-LAST:event_Carro2KeyReleased

    private void Tecla1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tecla1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Tecla1KeyReleased

    private void RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_RestartActionPerformed
 public void mover(){
     

addKeyListener(new KeyListener() {

    @Override

    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }
    

    @Override
    public void keyReleased(KeyEvent e) {
        
            if(e.getKeyCode()==let){
            if(posCarro1X>=560){
            posCarro1X=560;
                 ganhador.setVisible(true);
                 Perdedor.setVisible(true);
        }if(posCarro2X>=560){
            
        }
            else{
                 posCarro1X +=25;  
            } 
           if(posCarro1X>=560){
            posCarro1X=560;
                 ganhador.setVisible(true);
                 Perdedor.setVisible(true);
                 Restart.setVisible(true);
        }
            
            
            int [] abecedario = {65, 66, 67, 68 ,69, 70, 71, 72, 73, 
74, 75, 76,77,78,79,80,81,82,83,84,85,86, 87,88,89,90};

int numRandon = (int) Math.round(Math.random() * 25 ) ;

System.out.println( abecedario[numRandon] );

let= (char) abecedario[numRandon];
 if(let==let1){
     numRandon = (int) Math.round(Math.random() * 25);
     
                let= (char) abecedario[numRandon];
                
                
            }
Tecla1.setText(""+ let);
System.out.println(let);
   
            
        }      
            if(e.getKeyCode()==let1){
            
          
            if(posCarro2X>=560){
                posCarro2X=560;
                Ganhador2.setVisible(true);
                Perdedor2.setVisible(true);
            }if(posCarro1X>=560){
                
            }
             else{
                posCarro2X +=25;
            }
            if(posCarro2X>=560){
                posCarro2X=560;
                Ganhador2.setVisible(true);
                Perdedor2.setVisible(true);
                Restart.setVisible(true);
            }
            
            int [] abecedario1 = {65, 66, 67, 68 ,69, 70, 71, 72, 73, 
74, 75, 76,77,78,79,80,81,82,83,84,85,86, 87,88,89,90};

int numRandon1 = (int) Math.round(Math.random() * 25 ) ;

System.out.println( abecedario1[numRandon1] );

let1= (char) abecedario1[numRandon1];
if(let1==let){
    numRandon1 = (int) Math.round(Math.random() * 25);
     
                let1= (char) abecedario1[numRandon1];
                
            }
jLabel1.setText(""+ let1);
System.out.println(let1);
       
        }
            
            
        Carro1.setBounds(posCarro1X, posCarro1Y, 100, 40);
        Carro2.setBounds(posCarro2X, posCarro2Y, 110, 50);
        
           
/*Apatir daqui é o gerador de tecla do player 2*/
           
    }

}); 


}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cenario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carro1;
    private javax.swing.JLabel Carro2;
    private javax.swing.JLabel Cenario;
    private javax.swing.JLabel Ganhador2;
    private javax.swing.JLabel Perdedor;
    private javax.swing.JLabel Perdedor2;
    private javax.swing.JButton Restart;
    private javax.swing.JLabel Tecla1;
    private javax.swing.JLabel ganhador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables


 

}